### ISSUE TITLE
Draft the wireframe of the landing page

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#1]
Create a draft of the wireframe of the landing page for approval

**Comment by designeduard** [comment]
With which wireframe we go? Need this to move foward. Thanks

![Wireframe 2](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/28683c18-ff1c-4670-bd2a-7442a2e35533)
![untitled (1)](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/f9506665-1092-40be-bf54-1b7e75330cad)

**Comment by MQuesada99** [comment]
Hi @designeduard! Thank you for sharing the wireframes. We're waiting for the comments of @abetoluwani. I'll let you know as soon as we receive his feedback. Thank you! cc @faithobienu

**Comment by abetoluwani** [comment]
Approved wire frame is the second one 

But here are the changes i want made
-Student life should be replaced with gallery
-Enroll should be replaced with login
-About us should be at the footer don't too much things on top

Thanks

**Comment by abetoluwani** [comment]
@designeduard the colour code that should be on all pages

### Blue (Primary Color):
Use a shade of blue as the primary colour for elements like the header, navigation bar, and important sections. Blue represents trust, reliability, and professionalism, making it suitable for educational institutions.

### White (Background Colour):
Use white as the background colour to create a clean and minimalistic look. White provides a sense of openness, enhances readability, and allows other colours to stand out.

### Gray (Supporting Color):
Utilise various shades of grey for text, borders, and other supporting elements. Gray adds contrast, depth, and sophistication to the design. Use lighter shades of grey for backgrounds and darker shades for text and borders.

### Orange (Accent Color):
Use orange as an accent colour to add energy and draw attention to specific elements or call-to-action sections. Apply it sparingly for buttons, highlighted text, or important notifications.


### Usage for these colours:

- Blue: Header background, navigation bar, buttons, important headings.
- White: Overall background, content sections, text, and images.
- Gray: Borders, dividers, background for certain sections, text headings.
- Orange: Accent colour for buttons, call-to-action sections, or highlighted elements.


### Fonts: 

- Headings: Montserrat
- Body : Open Sans
