### ISSUE TITLE
As a user, I want to be able to view the Facilities and Learning Environment of the school so that I get a glimpse of the school's environment

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#11]
ESTIMATED TIME OF COMPLETION- 

ACCEPTANCE CRITERIA - this feature is considered done when i can get A glimpse into the well-equipped and child-friendly learning facilities, emphasizing the safe, vibrant, and engaging environment we provide for our students. This would include images of classrooms, play areas, libraries, and specialized learning spaces.

**Comment by designeduard** [comment]
@abetoluwani Please do leave feedback

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/6dad9945-9548-4a46-b5fb-4089f5070c63)

**Comment by abetoluwani** [comment]
Approved

You Should add a computer lab section here also

**Comment by designeduard** [comment]
This is a caroussel, it has multiple pages depends on how many facilities the school has, that lab can be implemented when developed for the second page. Or would be found on the Facilities subpages when done. Thank you

**Comment by abetoluwani** [comment]
ok
