### ISSUE TITLE
As a user, I want to be able to see the Student life of the school on the website, so that i can get an overview of the school's extracurricular activities

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#12]
ESTIMATED TIME OF COMPLETION - 

ACCEPTANCE CRITERIA - This feature is defined as done when the user can get An overview of the extracurricular activities, clubs, and events that contribute to a well-rounded student life experience. This would include information about sports, arts and crafts, music, field trips, and special celebrations.

**Comment by designeduard** [comment]
As requested to be gallery, please do feedback @abetoluwani

**Comment by designeduard** [comment]
![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/33291c82-6d58-4712-84bd-3f04c4df85fd)
