### ISSUE TITLE
Pupils Profile

### ISSUE THREAD

**Issue by abetoluwani** [mensapc/vrep-elementary-back#120]
This is based on the new ui

#Pupils Profile 
- [x] Pupils Name
- [x] Pupils ID
- [x] Gender
- [x] Class
- [x] Mother's Name
- [x] Father's Name
- [x] Registration Date
- [x] Address
- [x] Nationality (Takes The Fathers Nationality)
- [x] #124

#Pupils Profile (Exams)
- [x] Subject
- [x] Subject Teacher 
- [x] Date Of Exam
- [x] #130
- [x] #131
- [x] #132

#Pupils Profile (Exam Popup)
- [x] Subject 
- [x] Date Of Exam
- [x] Passing Percentage (50%)
- [x] Pupils Scores
- [x] Pupils Score Percentage
- [x] Time Range the Pupil Took The Exam

#Pupils Profile (Result)
- [x] Class Of The Result 
- [x] Term
- [x] View Details Would Be handled by the front end

#Pupil Profile (Teacher Remark)
- [ ] Teacher Remark
- [ ] Head Teachers Remark
- [ ] Punctuality
- [ ] Politeness
- [ ] Reading
- [ ] Honesty
- [ ] Verbal Fluency
- [ ] Behaviour
- [ ] Attitude
- [ ] Musical Skills
- [ ] Reliability
- [ ] Self-Control
- [ ] Creative Arts
- [ ] Attentiveness
- [ ] Teamwork Spirit
- [ ] Physical Edu.
- [ ] Mental Alertness
- [ ] Respect
- [ ] Initiatives
- [ ] Gen. Reasoning
- [ ] Neatness
- [ ] Handwriting
- [x] #125

**Comment by stawuah** [comment]
@muhenge  is working on the exam section after his refactor i will see what i can do

**Comment by abetoluwani** [comment]
Thank you very much @stawuah
