### ISSUE TITLE
Overall Total Score = Addition of a pupil score for every subject over hundred  as you can see in the picture we have the overall score of all subject by a pupil but not the overall total score  the Overall total score would be the addition of all these scores

### ISSUE THREAD

**Issue by stawuah** [mensapc/vrep-elementary-back#127]

**Comment by stawuah** [comment]
Here we have exam, but no `SUBJECT` and automatically it calculates the overall score by  100 
which is good, the teacher sets the exam with an exam name, so it is easy for a student to navigate and continue his/her test

**Comment by abetoluwani** [comment]
This is for the result view though

You should check the ui for more clarity

**Comment by stawuah** [comment]
- so the total score for a pupil needs to be the scores obtained by the pupil in each course.

This is what you mean right?
