### ISSUE TITLE
As a User, I want a Logo with similar design as the template so that i can use it as part of brand identity and content development

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#13]
Estimation time frame - 2 days

Acceptance criteria - The is defined as done when we have a logo that appeals to the users interests with the template provided.

- [ ] Share logo for approval
- [ ] share logo for ui/ux team

**Comment by faithobienu** [comment]
![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138668589/bf339cfd-af2b-4924-b9e7-ab3261189260)

**Comment by deji12** [comment]
Hi, i belong to the backend team
