### ISSUE TITLE
Time Range the Pupil Took The Exam

### ISSUE THREAD

**Issue by stawuah** [mensapc/vrep-elementary-back#132]

**Comment by stawuah** [comment]
I have a new modification 

- We call the `getTimeRangePupilTookExam ` function within the `getExamWithQustionsAndOptions` function to calculate the time range the pupil took the exam.

- If the user's role is a `pupil`, we check the `exam availability` and `calculate the time range`.

- We add the `calculated time range` to the exam object before sending it in the response.

 Now with this modification, when a pupil requests exam details, the response will include the calculated time range along with the exam details. This provides additional information about when the pupil took the exam.

**Comment by abetoluwani** [comment]
ok cool

**Comment by abetoluwani** [comment]
And also about the exam we would have to restructure the code to work like a google form add a question and add options afterwards

**Comment by stawuah** [comment]
Done on the backend 👌

**Comment by abetoluwani** [comment]
ok better 
because that's not how @RWUBAKWANAYO said he implemented it that's why

**Comment by stawuah** [comment]
Yes  and also @RWUBAKWANAYO  would have to brief @muhenge  and i on how he did the exam, but anyway to work like a Google form the changes need to be done on the UI the backend  can still remain the same
