### ISSUE TITLE
As a user, I want to be able to view Admission and Enrollment on the school's website so that i can get Information on the admission process, enrollment requirements, important dates, and contact details for prospective parents to inquire about admissions and schedule visits to the school.

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#14]
ESTIMATED TIME OF COMPLETION -

ACCEPTANCE CRITERIA - This is accepted as done if as a user, i can get Information on the admission process, enrollment requirements, important dates, and contact details for prospective parents to inquire about admissions and schedule visits to the school.

**Comment by designeduard** [comment]
@abetoluwani This is a CTA for admission, if user attention has been grabbed and wants 
to know more about the admission and details, this CTA would redirect 
them to a subpage containing all that informations

Please do leave a feedback, thanks

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/953db16d-8b96-4445-86c9-38d908959a18)

**Comment by designeduard** [comment]
The text button can be modified to ''Apply Now'' or ''Inquire Today''

**Comment by abetoluwani** [comment]
Inquire Today 

Approved
