### ISSUE TITLE
As a user, I want to be able to view News and Updates on the school's website so that i can get updates from the school

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#15]
ESTIMATED TIME OF COMPLETION -

ACCEPTANCE CRITERIA - This is accepted as done if as a user, I want A section featuring the latest news, announcements, and updates from the school. This may include upcoming events, achievements of students and faculty, and any important information relevant to the school community.

**Comment by designeduard** [comment]
![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/3abd3d36-a695-41fc-84b1-9f4efb5ef4eb)
