### ISSUE TITLE
VREP TEACHERS : SUBJECT IMPLEMENTATION 

### ISSUE THREAD

**Issue by abetoluwani** [mensapc/vrep-elementary-back#152]
- [x] SUBJECTS
> #### Edit Subjects
- Add Syllabus (Can Be Null-able) 
> #### List Of Subject
- Filter Subject {Latest,Oldest}
- The list of subject are based off the subject assigned to a class by the admin or head teacher

**Comment by NoamAvitan1** [comment]
subject implemented and completed by @stawuah and @NoamAvitan1
