### ISSUE TITLE
As a user, I want to be able to view the contact information of the school so that I can call them or schedule an appointment.

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#16]

**Comment by MQuesada99** [comment]
ESTIMATED TIME OF COMPLETION -

ACCEPTANCE CRITERIA - - Clear and easily accessible contact details, including the school's address, phone numbers, email addresses, and a contact form.

**Comment by designeduard** [comment]
Contact +  how messages would bee seen when someone is typing



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/4b96c8b7-ecad-46a3-b799-3f34065a39fb)
