### ISSUE TITLE
As a user, I want to be able to view School Newsletter Design so that i can view  informative newsletter about the school

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#17]
ESTIMATED TIME OF COMPLETION -

ACCEPTANCE CRITERIA - This story is defined as done if the School Newsletter Design is a visually appealing and informative newsletter template for the school, including sections for announcements, events, student achievements, and important dates.

**Comment by designeduard** [comment]
Not sure what you meant by this, but we discuss tonight, so I made a CTA block for parents to subscribe to the newsletter and have all updates and news in their inbox.

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/b5cfcf83-10d0-4cc9-b516-2a23a0763a89)
