### ISSUE TITLE
As a user, I want to register all my information so that I can login into the platform and edit my profile

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#18]
@RWUBAKWANAYO  and @deji12

**Comment by MQuesada99** [comment]
Estimated Time: PENDING

Acceptance Criteria: Registration and login functionality for students, teachers, administrators Access and permissions should depend on user type.

**Comment by COMMANDER-HOJAY** [comment]
https://github.com/Mensa-Philosophical-Circle/RPMS/tree/user-management/login%20web%20page

**Comment by COMMANDER-HOJAY** [comment]
This is just a preview on how the login interface will look like, i will commit to git at appropriate interval when the work is done..

**Comment by COMMANDER-HOJAY** [comment]
@abetoluwani
