### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#2]
@designeduard 

### Blue (Primary Color):
Use a shade of blue as the primary colour for elements like the header, navigation bar, and important sections. Blue represents trust, reliability, and professionalism, making it suitable for educational institutions.

### White (Background Colour):
Use white as the background colour to create a clean and minimalistic look. White provides a sense of openness, enhances readability, and allows other colours to stand out.

### Gray (Supporting Color):
Utilise various shades of grey for text, borders, and other supporting elements. Gray adds contrast, depth, and sophistication to the design. Use lighter shades of grey for backgrounds and darker shades for text and borders.

### Orange (Accent Color):
Use orange as an accent colour to add energy and draw attention to specific elements or call-to-action sections. Apply it sparingly for buttons, highlighted text, or important notifications.

### Usage for these colours:

- Blue: Header background, navigation bar, buttons, important headings.
- White: Overall background, content sections, text, and images.
- Gray: Borders, dividers, background for certain sections, text headings.
- Orange: Accent colour for buttons, call-to-action sections, or highlighted elements.

### Fonts: 

- Headings: Montserrat
- Body : Open Sans

    - [x] Create wireframes, mockups, and prototypes to propose a new UI/UX design for the school website.
    
    - [x] Ensure a consistent visual style, including colors, typography, and imagery, aligned with the school's branding guidelines.
    
    - [x]  Improve the website's navigation and information architecture to enhance user flow and accessibility.
    
    - [x] Implement responsive design principles to ensure a seamless experience across different devices and screen sizes.
    Optimize the website's performance and loading speed to minimize user frustration.

**Comment by designeduard** [comment]
This is how the whole landing page looks when all sections are put together @abetoluwani @faithobienu @MQuesada99 



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/27f45323-229e-4e87-95a4-d4b45fe01f7b)

**Comment by faithobienu** [comment]
@mofopeadegoke kindly view
