### ISSUE TITLE
As a user, I want to communicate with other users so that I can share announcements , new updates and events

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#24]
Estimated Time: PENDING

Acceptance criteria:

Implement a messaging system for communication between students, teachers, and administrators.
Provide a platform for important announcements, news updates, and event notifications.
Allow teachers and administrators to send notifications to students and parents.

@RWUBAKWANAYO  and @deji12

**Comment by MQuesada99** [comment]
Estimated Time: PENDING

Acceptance criteria: 
   - Implement a messaging system for communication between students, teachers, and administrators.
   - Provide a platform for important announcements, news updates, and event notifications.
   - Allow teachers and administrators to send notifications to students and parents.

**Comment by COMMANDER-HOJAY** [comment]
https://github.com/Mensa-Philosophical-Circle/RPMS/tree/user-management/landing%20page
