### ISSUE TITLE
Academic Entities

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#28]
Estimated Time: PENDING

Acceptance Criteria:

-Course: Create a "Course" table to store course information like course ID, title, description, and other relevant details.
-Class: Create a "Class" table to represent individual classes offered by the school. Include attributes like class ID, course ID (foreign key), teacher ID (foreign key), schedule, and classroom details.

**Comment by MQuesada99** [comment]
@deji12

**Comment by faithobienu** [comment]
Students table:
student_id (primary key)
student_name
student_email
other relevant student details

Courses table:
course_id (primary key)
course_name
course_description
other relevant course details

Assessments table:
assessment_id (primary key)
course_id (foreign key referencing the Courses table)

assessment_name
assessment_type (e.g., test, exam, project)
maximum_score
assessment_date
other relevant assessment details

Grades table:
grade_id (primary key)
student_id (foreign key referencing the Students table)
assessment_id (foreign key referencing the Assessments table)
score
other relevant grade details
