### ISSUE TITLE
Database architecture/configuration

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#4]
Technologies Used = Python, Firebase and MySQl  @RWUBAKWANAYO and @deji12 

#7 
#27 
#28 
#29 
#30 
#39 
#41 
#40

**Comment by ZeberMVP** [comment]
I'm not in the backend team

**Comment by MQuesada99** [comment]
Hi @ZeberMVP! You're right, you're part of the Front-end team. @faithobienu I apologize for the confusion

**Comment by deji12** [comment]
Hi there. I think i and the other backend devs need to talk about this, and what backend language or languages will be suitable for the task. I personally would suggest python and Django. Django has an excellent ORM that makes writing queries and interacting with the database super easy and convenient

**Comment by faithobienu** [comment]
> Hi there. I think i and the other backend devs need to talk about this, and what backend language or languages will be suitable for the task. I personally would suggest python and Django. Django has an excellent ORM that makes writing queries and interacting with the database super easy and convenient

Okay, thank you for your suggestion @deji12 we are expecting the rest of the team here latest start of work tomorrow. I am sure we'd conclude on that before we start the tasks allocation etc

**Comment by deji12** [comment]
Hm, hi guys. I just wanted to mention that i am not familiar with Node Js and firebase. I work with python and django
