### ISSUE TITLE
Landing Page Wire Frame For The Front End

### ISSUE THREAD

**Issue by abetoluwani** [mensapc/vrep-elementary-back#46]
@designeduard  i need the landing page wire frame so that @ZeberMVP  can start working on that 

Deadline : Tomorrow 

@MQuesada99 and @faithobienu

**Comment by designeduard** [comment]
Landing Page UI/UX Design @MQuesada99 @faithobienu 

1. Need LOGO
2. Need Feedback
3. Need to speak with front end team to share the file so they can develop it accordingly.

Thanks
![_1440px](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/036df6c2-312e-4223-8f45-17c1ee13fbc3)

**Comment by abetoluwani** [comment]
Waiting for the graphic designer team to provide the  logo

**Comment by faithobienu** [comment]
I believe the front end team can start with this wireframe while waiting for logo design. I'll also check up with @menaka32 again on this.

Thanks
