### ISSUE TITLE
As a user, I want to be able to see the school's Mission and Values so that I get more information about the school from the website

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#5]

**Comment by faithobienu** [comment]
ETC -

AC -
The task is seen as done when the user gets an overview of the school's mission and core values, highlighting their educational philosophy and the principles that guide our teaching and interactions with students.

**Comment by designeduard** [comment]
Mission and values, goes, please do leave feedback @abetoluwani 

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/83d3c72e-3094-46cd-ac60-cd6165061f4b)

**Comment by abetoluwani** [comment]
I need the all the ui ux design compiled so that the front end team can start working on it @designeduard

**Comment by designeduard** [comment]
We will discuss in today's meeting I believe, I'll have a chat with Faith, Miquel and front-end team
