### ISSUE TITLE
Facilities and Learning Environment

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#54]
A glimpse into the well-equipped and child-friendly learning facilities, emphasising the safe, vibrant, and engaging environment we provide for our students. This would include images of classrooms, play areas, libraries, and specialised learning spaces.

**Comment by designeduard** [comment]
@abetoluwani @faithobienu @MQuesada99 reviews, more images gonna be on the gallery section to watch.

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/2e2c7155-b6b1-4915-9faa-8c7a4ef49c2e)

**Comment by abetoluwani** [comment]
the  connect with us does not need to be on all pages

**Comment by abetoluwani** [comment]
@designeduard concerning your question YES
