### ISSUE TITLE
Programs

### ISSUE THREAD

**Issue by designeduard** [mensapc/vrep-elementary-back#56]
All programs

**Comment by designeduard** [comment]
![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/f47edb78-ecd6-4fb8-b871-175fb796aa9c)



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/cbbaacf4-79da-4f95-8a95-e127e819382d)



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/af94a436-31b2-4835-976e-cc1adf76acb7)



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/12fbd0a4-b61a-45f5-944c-905f19ed7274)

**Comment by abetoluwani** [comment]
Check my message at Issue #54
