### ISSUE TITLE
As a user, I want a School Introduction that is warm and inviting so that student, teachers and Parents can use easily

### ISSUE THREAD

**Issue by MQuesada99** [mensapc/vrep-elementary-back#8]

**Comment by faithobienu** [comment]
Estimated time for completion - 2 days

AC - This task is defined as done when the school Introduction is seen as  warm and inviting introduction of school, emphasising their commitment to fostering holistic development, promoting creativity, and instilling a love for learning.

**Comment by designeduard** [comment]
@abetoluwani This is the Introduction + header for the school website.

Please do leave a feedback on it.

Thanks



![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/03ebfe02-5bb1-46bc-8031-740357fd1ff4)

**Comment by abetoluwani** [comment]
@designeduard this really looks nice carry on

@faithobienu  and @MQuesada99  any input

**Comment by abetoluwani** [comment]
and also try to implement the colour code stated in #1  on qll your designs

**Comment by designeduard** [comment]
Primary color says to be a shade of blue, personally if we use the main blue would be to harm for user eyes, so i went for a calmer shade which doesnt bother the eye that much, if you know what I mean

**Comment by designeduard** [comment]
That's how we designers are teached to to, thank you
