### ISSUE TITLE
As a user, I want to be able to view Programs and Curriculum of the school so i know what the school offers

### ISSUE THREAD

**Issue by faithobienu** [mensapc/vrep-elementary-back#9]
ETC - 

AC - This story is considered done when Details about the Montessori, Kindergarten, Nursery, and Primary programs they offer, including a brief description of each level's curriculum, teaching methods can be seen on the website

**Comment by designeduard** [comment]
@abetoluwani This is Programs and Curiculum Section, please do leave a feedback

Thanks

![Image](https://github.com/Mensa-Philosophical-Circle/RPMS/assets/138588964/910e5202-fe62-4c43-93cf-e50e1798aeb4)

**Comment by abetoluwani** [comment]
Es perfecto @designeduard 
For me this is good
any thoughts @faithobienu and @MQuesada99
