### ISSUE TITLE
RPMS BACK (Admin) : Pupils Profiles

### ISSUE THREAD

**Issue by abetoluwani** [mensapc/vrep-elementary-back#92]
- [x] Restrict pupils from logging in by the admin

**Comment by stawuah** [comment]
@abetoluwani This issue has a solution already, we have RBAC on pupils which determines their access permissions. Unless you would want a feature specifically for restricting pupils from logging in as the admin. which might be a **potential future enhancement**

**Comment by abetoluwani** [comment]
Ooh okay
